---
abstract: 'Poor-mans grid computing via SSH'
author:
  - 'Stefan Seemayer <seemayer@rostlab.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SSHGrid
provides:
  SSHGrid:
    file: lib/SSHGrid.pm
    version: 0.01
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
