#!/bin/bash

# worker script for SSHGrid
queuefile=$1
lockfile=$2
hostnumber=$3
hostcount=$4

function get_next_task {
	(
		# get exclusive access to queuefile
		flock 100

		# get first line in queuefile
		task=$(head -n1 $queuefile);
		
		# delete first line in queuefile
		sed -i '1d' $queuefile
		
		echo $task

	) 100>$lockfile
}


function log {
	timestamp=`echo -e "\`date\` ($hostnumber/$hostcount)\t"`
	echo "${timestamp}$*"
}

function execute_task {

	task=$*

	log "Executing '$task'"

	process_task
	bash -c "$task" || log "WARNING: Failed with exit code $?"
}

function process_task {
	task=$( echo $task | sed -e "s/\$hostnumber/$hostnumber/g" )
}

function wait_barrier {

}

function barrier_passed {

}

log "Started worker on `hostname`"

next_task=$(get_next_task)
while [ "$next_task" != "" ]; do

	# determine what line we encountered
	if [[ ${next_task:0:1} != "#" ]]; then
		# task line, just execute the task
		execute_task $next_task

	elif [[ ${next_task:0:3} == "#%B" ]]; then
		# barrier, wait for other workers
		log "Encountered barrier"
		wait_barrier
	else
		# comment line, ignore it
		log "Ignored comment $next_task"
	fi

	next_task=$(get_next_task)
done


log "Finished."

# vim filetype=bash
