#!/bin/bash

# worker script for SSHGrid
queuefile=$1
lockfile=$2
hostnumber=$3

function get_next_task {
	(
		# get exclusive access to queuefile
		flock 100

		# get first line in queuefile
		task=$(head -n1 $queuefile);
		
		# delete first line in queuefile
		sed -i '1d' $queuefile
		
		
		echo $task

	) 100>$lockfile
}

function process_task {
	next_task=$( echo $next_task | sed -e "s/\$hostnumber/$hostnumber/g" )
}

echo -e "`date`\tStarting"

next_task=$(get_next_task)
while [ "$next_task" != "" ]; do

	echo -e "`date`\tExecuting '$next_task'"

	process_task
	bash -c "$next_task"

	next_task=$(get_next_task)
done

echo -e "`date`\tFinished."

# vim filetype=bash
